alcher/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
urlpatterns = [
    path('',RedirectView.as_view(url  ='/auths/login/')),
    path('admin/', admin.site.urls),
    path('auths/', include('auths.urls', namespace='auths')),
    path('caportal/', include('ca.urls', namespace='ca')),
    path("fbshare/",include("fbshare.urls",namespace="fb")),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(template_name="auths/password_reset_form.html"), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name="auths/password_reset_done.html"), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name="auths/password_reset_confirm.html"), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(template_name="auths/password_reset_complete.html"), name='password_reset_complete'),
]

#urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

auths/urls.py
from django.urls import path, re_path
from . import views as auths_views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls import include



app_name = 'auths'

urlpatterns = [
    path('register/', auths_views.register, name="register"),
    path('home/', TemplateView.as_view(template_name="auths/home.html"), name="home"),
    path('login/', auths_views.login, name='login'),
    path('verifymail/', auths_views.verifyEmail, name='verifyEmail'),
    path('logout/', auths_views.logout_, name='logout'),
    path('social-auth/', include('social_django.urls', namespace="social")),
    # path('register_oauth/', auths_views.register_oauth, name="register_oauth"),
    path('account_activation_sent/', auths_views.account_activation_sent, name='account_activation_sent'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
    	auths_views.activate, name='activate'),
    path('resendmail/' , auths_views.resendMail, name='resendMail'),
    
]

ca/urls.py
from django.urls import path
from . import views

app_name = 'ca'

urlpatterns = [
    path('home', views.home, name='home'),
    path('contact', views.contactUs , name='contactUs'),
    path('faqs', views.faqs , name='faqs'),
    # path('venue', views.venue , name='venue'),
    path('questionnaire', views.questionnare, name='questionnare'),
    path('pending', views.pending, name='pending'),
    path('guidelines', views.guidelines, name='guidelines'),
    path('hospitality', views.hospitality, name='hospitality'),
    path('poc', views.poc, name='poc'),
    path('submitideas', views.submitIdea, name='submitIdea'),
    path('standings', views.standings, name='standings'),
    path('notifications', views.notifications, name='notifications')
]

fbshare/urls.py
from django.urls import path 
from .views import *

app_name = "fb"
urlpatterns = [
        path("fb/",view=fb),
        path("invite/" ,view = invite_all,name ="invite_all")
        ]

ca/views.py
from django.shortcuts import render, redirect
# from ca.models import Notifications, Idea, Complaints, FAQ, Venue, CA_Questionnaire, POC, TriweekyWinner
from ca.models import Notifications, Idea, Complaints, FAQ, Venue, POC, CA_Questionnaire
from auths.models import CA_Detail
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from random import randint
from django.core.validators import RegexValidator, EmailValidator, URLValidator
from auths.models import CA_Detail
from .decorators import profile_required
from django.contrib.auth.models import User
from .choices import STATE_CHOICES

def generateGrievanceId():
        try:
                lpk = Complaints.objects.last().pk+1
        except Exception as e:
                lpk = 1
        return "CX"+str(randint(1563,9874))+str(lpk)

@login_required
@profile_required
def notifications(request):
        all_notifications = Notifications.objects.filter(notification_receiver = request.user)
        sendToAll = User.objects.get(username="sendToAll")
        all_notifications |= Notifications.objects.filter(notification_receiver = sendToAll)
        all_notifications = all_notifications.order_by('-notification_timestamp')[:5]
        return render(request, "ca/notifications.html", {'all_notifications': all_notifications})

@login_required
@profile_required
def contactUs(request):
        if request.method == 'POST':
                COMPLAINT_CATEGORY_CHOICES = {
                ('General', 'General'),
                ('Technical', 'Technical'),
                ('Competition', 'Competition'),
                ('Festival', 'Festival'),
                ('Payment', 'Payment'),
                }
                complaint_category_list = [x[0] for x in COMPLAINT_CATEGORY_CHOICES]
                data = {}
                if request.POST['complaint_category'] == '':
                         data['complaint_category_stat'] = "Complaint category empty"
                if request.POST['complaint_category'] not in complaint_category_list:
                         data['complaint_category_stat'] = "INVALID COMPLAINT CATEGORY"

                if request.POST['complaint_text'] == '':
                         data['complaint_text_stat'] = "Complaint text empty"

                if data.get('category') or data.get('desc'):
                        data['stat'] = "FAILURE"
                        return JsonResponse(data)
                else :
                        complaint_text = request.POST['complaint_text']
                        complaint_category = request.POST['complaint_category']
                        grievance_id = generateGrievanceId()

                        Complaints.objects.create(user=request.user, complaint_text=complaint_text, 
                                complaint_category=complaint_category, grievance_id=grievance_id)
                        data['grievance_id']= grievance_id
                        data['stat'] = "SUCCESS"

                return JsonResponse(data)
        else:
                
                prevQueries = Complaints.objects.filter(user=request.user).order_by('-pk')

                context = {
                'prevQueries': prevQueries,
                'more_active': True,
                }

                return render(request, 'ca/contacts.html', context)


@login_required
@profile_required
def submitIdea(request):
        if request.method == 'POST':
                IDEA_CATEGORY_CHOICES = {
                ('Competition', 'Competition'),
                ('Workshop', 'Workshop'),
                ('Hospitality', 'Hospitality'),
                ('Artist', 'Artist'),
                ('Crowd Experience', 'Crowd Experience'),
                ('Other', 'Other'),
                }
                idea_category_list = [x[0] for x in IDEA_CATEGORY_CHOICES]
                data = {}
                if request.POST['idea_category'] == '' or request.POST['idea_category'] not in idea_category_list:
                         data['category'] = "Category Empty"

                if request.POST['idea_desc'] == '':
                         data['desc'] = "Desc Empty"

                if data.get('category') or data.get('desc'):
                        data['stat'] = "Failure"
                        return JsonResponse(data)
                else :
                        idea = request.POST['idea_desc']
                        idea_category = request.POST['idea_category']
                        Idea.objects.create(user=request.user, idea=idea, idea_category=idea_category)
                        data['stat'] = "Success"

                return JsonResponse(data)
        else:
                
                ideaQueries = Idea.objects.filter(user=request.user).order_by('-pk')

                context = {
                        'ideaQueries': ideaQueries,
                        'idea_active': True,
                }

                return render(request, 'ca/idea.html', context)

@login_required
@profile_required
def faqs(request):
        if request.method == 'POST':
                faq_category = request.POST['faq_category']
                faqs = FAQ.objects.filter(faq_category=faq_category)

                context = {
                'faqs':faqs,
                }

                return render(request, 'ca/faq_response.html', context)

        else:
                return render(request, 'ca/faq.html', {'more_active': True})


@login_required
@profile_required
def venue(request):
        if request.method == 'POST':
                
                data = {}
                if request.POST['venue_name'] == '':
                        data['venue_name'] = "Venue Name Empty"
                
                if request.POST['contact_person'] == '':
                        data['contact_person'] = "Contact Person Empty"
                else:
                        contact_number_validator = RegexValidator('^[0-9]{10}$')
                        try:
                                contact_number_validator(request.POST['contact_number'])
                        except Exception as e:
                                data['contact_number'] = "Contact Number REGEX"



                if request.POST['contact_number'] == '':
                        data['contact_number'] = "Contact Number Empty"

                if request.POST['venue_address'] == '':
                                         data['venue_address'] = "Venue Address Empty"

                
                

                if data:
                        data['stat'] = "FAILURE"
                        return JsonResponse(data)
                else :
                        venue_name = request.POST['venue_name']
                        contact_person = request.POST['contact_person']
                        contact_number = request.POST['contact_number']
                        venue_address = request.POST['venue_address']
                        remarks = request.POST['remarks']
                        Venue.objects.create(user=request.user, venue_name=venue_name, contact_name=contact_person,
                                contact_number=contact_number, venue_address=venue_address, remarks=remarks)
                        data['stat'] = "Success"

                        return JsonResponse(data)

        else:
                
                venues = Venue.objects.filter(user=request.user).order_by('-pk')
                name_pattern = "[A-Za-z ]+"
                team_name_pattern = "[A-Za-z0-9, ]+"
                phone_pattern = "[0-9]{10}"

                context = {
                'venues': venues,
                'name_pattern':name_pattern,
                'team_name_pattern':team_name_pattern,
                'phone_pattern':phone_pattern,
                'more_active': True,
                }

                return render(request, 'ca/venue.html', context)



@login_required
def questionnare(request):
        if request.method == 'POST':
                data = {}
                college_name_validator = RegexValidator('^[a-zA-z0-9, ]*$')
                if request.POST['college_name'] == '':
                        data['college_name_stat'] = "COLLEGE NAME EMPTY"
                else:
                        try:
                                college_name_validator(request.POST['college_name'])
                        except Exception as e:
                                data['college_name_stat'] = "COLLEGE NAME REGEX"

                try:
                        alcherid_validator = RegexValidator('^((ALC)-[A-Z]{3}-[0-9]*)?$')
                        alcherid_validator(request.POST['referral'])
                except Exception as e:
                        data['referral_stat'] = "REFERRAL REGEX"
                else:
                        if request.POST['referral'] == request.user.profile.alcher_id:
                                data['referral_stat'] = "ALCHER ID"

                try:
                        college_name_validator(request.POST['por'])
                except Exception as e:
                        data['por_stat'] = "POR REGEX"

                city_validator = RegexValidator('^[a-zA-z0-9,-: ]+$')
                if request.POST['city'] == '':
                        data['city_stat'] = "CITY EMPTY"
                else:
                        try:
                                city_validator(request.POST['city'])
                        except Exception as e:
                                data['city_stat'] = "CITY REGEX"
                                


                if request.POST['mailing_address'] == '':
                        data['mailing_address_stat'] = "MAILING ADDRESS EMPTY"
                else:
                        try:
                                city_validator(request.POST['mailing_address'])
                        except Exception as e:
                                data['mailing_address_stat'] = "MAILING ADDRESS REGEX"

ca/templates/ca/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
{#  	<meta name="author" content="Kishor Malakar">#}
{#  	<link rel="author" href="https://www.facebook.com/kishor.malakar" />#}
    
{% load static %}

    <style>
      @media only screen and (max-width: 990px) {
        .navbar-nav{
          z-index: 10;
        }
      }
      .mdl-textfield{
        max-width: 95%;
      }
    </style>
  <link rel="stylesheet" href="{% static 'ca/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'ca/css/index.css' %}">
  <link rel="stylesheet" href="{% static 'ca/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'ca/css/Roboto.css' %}">
  <link rel="stylesheet" href="{% static 'ca/css/normalize.css' %}">
  	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  	<link href="https://fonts.googleapis.com/css?family=Fira+Sans|Roboto" rel="stylesheet">
    <!-- <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.teal-green.min.css"> -->
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.teal-green.min.css" />
  	<link rel="stylesheet" href="{% static 'ca/css/semantic.min.css' %}">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  	<link rel="icon" type="image/png" href="{% static 'ca/img/favicon.png' %}">
  	<meta name="theme-color" content="#455A64">

  	<meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
      {% block title %}
      {% endblock %}
{#       | Campus Ambassador | Alcheringa, IIT Guwahati#}
    </title>
  </head>
  <body style="background-color: #C9D1D3">
    <nav class="navbar navbar-expand-lg navbar-custom navbarParent" >
    	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCustom" aria-controls="navbarCustom" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"><img src="{% static 'ca/img/List (2).png' %}"></span>
  </button>
      <a href="{% url 'ca:home' %}" class="navbar-brand navbarBrandCustom">
      	<img src="{% static 'ca/img/logo black-1 (2).svg' %}" class="d-inline-block align-top">
      </a>

      <div class="navbar-collapse collapse" id="navbarCustom" style="z-index: 10;">
        <span class="navbar-text " id="navbarItems">
          <ul class="navbar-nav">
            <li class="nav-item {% if home_active %} active {% endif %} ml-2 mr-2">
              <a class="nav-link" href="{% url 'ca:home' %}">HOME </a>
            </li>
            <!-- <li class="nav-item {% if dashboard_active %} active {% endif %}  ml-2 mr-2">
              <a class="nav-link" href="#">DASHBOARD </a>
            </li> -->
            <li class="nav-item {% if guidelines_active %} active {% endif %}  ml-2 mr-2">
              <a class="nav-link" href="{% url 'ca:guidelines' %}">GUIDELINES </a>
            </li>
            <li class="nav-item {% if idea_active %} active {% endif %} ml-2 mr-2">
              
              <a class="nav-link" href="{% url 'ca:standings' %}"> STANDINGS </a>
            </li>
            
            <li class="nav-item {% if more_active %} active {% endif %} dropdown">
              <a class="nav-link dropdown-toggle ml-2 mr-2" id="navbarDropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false" style="cursor: pointer; ">MORE.. </a>
              <div class="dropdown-menu dropdown-primary navbarDropdown" aria-labelledby="navbarDropdownMenuLink1">
                
                <!-- Load the template tag for the url -->
                <!-- <a class="dropdown-item navbarDropdownItem" href="% url 'ca:venue' %"> SUBMIT VENUE </a> -->
                <a class="dropdown-item navbarDropdownItem" href="{% url 'ca:poc' %}"> SUBMIT POC </a>
                <!-- <a class="dropdown-item navbarDropdownItem" href="{% url 'fb:invite_all' %}">SUBMIT FBINVITES </a> -->
                <a class="dropdown-item navbarDropdownItem" href="{% url 'ca:submitIdea' %}">SUBMIT IDEAS </a>
                <!-- <a class="dropdown-item navbarDropdownItem" href="{% url 'ca:hospitality' %}"> HOSPITALITY </a> -->
                <a class="dropdown-item navbarDropdownItem" href="{% url 'ca:faqs' %}"> FAQ </a>
                <a class="dropdown-item navbarDropdownItem" href="{% url 'ca:contactUs' %}"> CONTACT US </a>
                <a class="dropdown-item navbarDropdownItem" href="{% url 'auths:logout' %}"> LOGOUT </a>
              </div>
            </li>


          </ul>
        </span>
      </div>
      <span id="profileImage" style="z-index: 10;">
      <ul class="nav navbar-nav navbar-right">
      <li class="nav-item"><a href="#"><img style="border-radius: 50%;
  width: 40px;
  height: 40px;
" src="{% static 'ca/img/Avatar.png' %}"></a></li>
    </ul>
</span>
    </nav>
    <br><br><br>
    <div class="container-fluid">
    <div class="row">
  <div class=" col-lg-3 d-none d-lg-block" style="padding-left: 3rem;">
    <div class="card">
      <div class="card-body">
        <p class="card-image" style="text-align: center;">
          <img src="{% static 'ca/img/Avatar.png' %}" style="border-radius: 50%; width: 150px; height: 150px;" >
        </p>
        <p class="card-title" style="text-align: center;">
          <h3><!--NAME--></h3>
          </p>
          <br>
        <div class="card-text">
        <div style="float: left;"> Alcher ID: </div><div style="float: right;"> {{ user.profile.alcher_id }}</div><br><br>
        <div style="float: left;"> Score: </div><div style="float: right;"> {{ user.ca_details.score }}</div><br><br>
         {% comment %} <div style="float: left;"> Tri-weekly Score: </div><div style="float: right;">
          {{ user.ca_details.triweekly }}
        </div>
        <br><br>  {% endcomment %}
        </div>
      </div>
    </div>
  </div>

{% block body %}
{% endblock %}
  
	<div aria-live="assertive" aria-atomic="true" aria-relevant="text" class="mdl-snackbar mdl-js-snackbar">
	    <div class="mdl-snackbar__text"></div>
	    <button type="button" class="mdl-snackbar__action"></button>
	</div>

	<script type="text/javascript" src="{% static 'ca/js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'ca/js/drawer.js' %}"></script>
	<script type="text/javascript" src="{% static 'ca/js/jquery_ui/jquery-ui.min.js' %}"></script>
	<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
	<script type="text/javascript" src="{% static  'ca/js/semantic.min.js'%}"></script>
  {% block js %}
  {% endblock %}

   <div class="col-lg-3 d-none d-lg-block" style="padding-right: 3rem;">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Notification</h4>
        {% for notification in notifications %}
        <a href="{{notification.notification_href}}" style="color: inherit; ">
        <p class="card-text" > {{ notification.notification_content|truncatechars:120 }}</p>
        </a>
        <hr>
        {% endfor %}
        <a href="{% url 'ca:notifications' %}">See All </a>
      </div>
    </div>
  </div>
</div>
</div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

ca/templates/ca/faq_response.html
<div id='accordion'>
	{% for faq in faqs %}
	<h3><span class='material-icons'>contact_support</span>{{faq.faq_question}}</h3>
	<div><p>{{faq.faq_answer}}</p></div>
	{% endfor %}
</div>

ca/templates/ca/home.html
{% extends 'ca/base.html' %}
    {% load static %}



{% block title %}Home | Campus Ambassador | Alcheringa, IIT Guwahati{% endblock %}

{% block body %}
	<div class="col-lg-6">
				<div class="content_home">
					<div class="notifications_div">
						<!-- <div class="notification_header">
							<p>Notifications</p>
						</div> -->
						<div class="notification_content">
						</div> <!-- notification_content -->
					</div> <!-- notifications_div -->
					<div class='referral_div d-block d-lg-none'>
						<div class='referral_header'>
							<p>MY PROFILE</p>
						</div>
						<div class="card">
							<div class="card-body">
							  <p class="card-image" style="text-align: center;">
								<img src="/media/{{user.profile.profile_image}}" style="border-radius: 50%; width: 150px; height: 150px;" >
							  </p>
							  <p class="card-title" style="text-align: center;">
								<h3><!--NAME--></h3>
								</p>
								<br>
							  <div class="card-text">
							  <div style="float: left;"> Alcher ID: </div><div style="float: right;"> {{ user.profile.alcher_id }}</div><br><br>
							  <div style="float: left;"> Score: </div><div style="float: right;"> {{ user.ca_details.score }}</div><br><br>
							   {% comment %} <div style="float: left;"> Tri-weekly Score: </div><div style="float: right;">
								{{ user.ca_details.triweekly }}
							  </div>
							  <br><br>  {% endcomment %}
							  </div>
							</div>
						  </div>
					</div>

					<div class='referral_div'>

						<div class='referral_header'>
							<p>Referral Code</p>
						</div>
						<div class='referral_content'>
							<div class="referral_details">
								<p>Your referral code is</p>
								<h4 style="background-image: url({% static 'ca/img/ribbon.png' %});">{{ user.profile.alcher_id }}</h4>
								<p>Share this with your Friends and make them a part of Alcheringa. In turn get bounty points and awesome prizes.</p>
							</div>
							<!-- <div class="referral_action">
								<button class='share_referral ui button' <?php echo "alcher_id='$alcher_id'"; ?>>Share</button>
							</div> -->
						</div>

					</div> 
					
					<div class='referral_div d-block d-lg-none'>

						<div class='referral_header'>
							<p>Notifications</p>
						</div>
						<div class='referral_content'>
							{% for notification in notifications %}
							<a href="{{notification.notification_href}}" style="color: inherit; ">
							<p class="card-text" > {{ notification.notification_content|truncatechars:120 }}</p>
							</a>
							<hr>
							{% endfor %}
							<a href="{% url 'ca:notifications' %}">See All </a>
						</div>

					</div> 
					
					<!-- referral_div -->

					<!-- <div class='time_remaining_div'>

						<div class="time_remaining_header">
							<p>Next Tri Weekly</p>
						</div>

						<div class="time_remaining_content">

						</div>

					</div> -->

				</div> <!-- content_home -->
		
	</div><!-- .wrapper -->

	<div aria-live="assertive" aria-atomic="true" aria-relevant="text" class="mdl-snackbar mdl-js-snackbar">
	    <div class="mdl-snackbar__text"></div>
	    <button type="button" class="mdl-snackbar__action"></button>
	</div>

	<script type="text/javascript" src="{% static 'ca/js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'ca/js/drawer.js' %}"></script>
	<script type="text/javascript" src="{% static 'ca/js/jquery_ui/jquery-ui.min.js' %}"></script>
	<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
	 <script type="text/javascript">
  		window.fbAsyncInit = function() {
  	  FB.init({
      		appId            : '963688477438734',
      		autoLogAppEvents : true,
     		 xfbml            : true,
      		version          : 'v8.0'
    	});
  };
    </script>
   <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js"></script>
    
	<script type="text/javascript">
		$(function(){

			

			$('.share_referral').click(function(){

				$(this).addClass('loading');
				var $this = $(this);
				var alcher_id = $this.attr('alcher_id');

		    /* FB.ui(
					{
					method: 'share_open_graph',
					action_type: 'news.publishes',
					hashtag: '#HailAlcher',
					share_referral :"sdfafaf" 
					action_properties: JSON.stringify({
					    article : {
					    	   'fb:app_id': '963688477438734',
					           'og:url': 'http://www.alcheringa.in/ca/',
					           'og:type': 'article',
					           'og:title': 'Be a part of Alcheringa, IIT Guwahati. Use referral code '+alcher_id+'.',
					           'og:description': 'I have enrolled myself for the Campus Ambassador Programme of Alcheringa, IIT Guwahati.',
					           'og:image': 'http://alcheringa.in/ca/ca_try.png',
					        }
					  })
					}, */ 
				 FB.ui(
					{
						
					method: 'share',
					href:"www.alcheringa.in/ca/",
					hashtag : "#HailAlcher",
					type:'article',
					
				}, function(response){

						$this.removeClass('loading');

	    				if(response && !response.error_message){

	    					var notification = document.querySelector('.mdl-js-snackbar');
	    					var data = {
	    					  message: 'Post shared on Facebook',
	    					  timeout: 2000
	    					};
	    					notification.MaterialSnackbar.showSnackbar(data);
	    					
	    				}

	    				else if(response && response.error_message){

	    					var notification = document.querySelector('.mdl-js-snackbar');
	    					var data = {
	    					  message: 'Error ! Post couldnot be shared',
	    					  timeout: 2000
	    					};
	    					notification.MaterialSnackbar.showSnackbar(data);

	    				}

	    				else if(!response){

	    					var notification = document.querySelector('.mdl-js-snackbar');
	    					var data = {
	    					  message: 'Did you change your mind?',
	    					  timeout: 2000
	    					};
	    					notification.MaterialSnackbar.showSnackbar(data);

	    				}

					});

			});

			$('.notification').click(function(){
				var $this= $(this);
				var notification_id= $this.attr('data-notification-id');
				var notification_href= $this.attr('data-notification-href');

				$.ajax({
					type: "POST",
					url: "notification_read.php",
					dataType: 'json',
					data: {notification_id: notification_id},
					success: function(response){
						if(response.session == "Session Error"){
							var notification = document.querySelector('.mdl-js-snackbar');
							var data = {
							  message: 'Session Expired',
							  timeout: 2000
							};
							notification.MaterialSnackbar.showSnackbar(data);

							setTimeout(function(){
								window.location.href = "index.php";
							}, 3000);
						}

						else if(response.stat=="Notification read"){
							if(notification_href === "#"){
								window.location.href = "notifications.php";
							}
							else{
								window.location.href = notification_href;
							}
						}
						else if(response.stat=="Notification already read"){
							if(notification_href === "#"){
								window.location.href = "notifications.php";
							}
							else{
								window.location.href = notification_href;
							}
						}
						else if(response.stat=="Failure"){

						}
					}
				});
			});

			var triweekly = ["09/10/2017", "10/01/2017", "10/22/2017", "11/12/2017", "12/03/2017", "12/24/2017", "01/15/2018", "02/05/2018"];
			var today = new Date();

			for(i = 0; i < triweekly.length; i++){

				var triweekly_date = new Date(triweekly[i]);

				var diffTime = triweekly_date.getTime() - today.getTime();
				var diffDays = Math.ceil(diffTime / (1000 * 3600 * 24));

				if(diffDays >= 0){

					if(diffDays == 1){
						$('.time_remaining_content').html("<div><p>"+diffDays+"</p></div><p> Day to Go</p>");
						break;
					}
					else{
						$('.time_remaining_content').html("<div><p>"+diffDays+"</p></div><p> Days to Go</p>");
						break;
					}

				}

			}



		});
	</script>

{% endblock %}