alcher/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
urlpatterns = [
    path('',RedirectView.as_view(url  ='/auths/login/')),
    path('admin/', admin.site.urls),
    path('auths/', include('auths.urls', namespace='auths')),
    path('caportal/', include('ca.urls', namespace='ca')),
    path("fbshare/",include("fbshare.urls",namespace="fb")),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(template_name="auths/password_reset_form.html"), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name="auths/password_reset_done.html"), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name="auths/password_reset_confirm.html"), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(template_name="auths/password_reset_complete.html"), name='password_reset_complete'),
]

#urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

auths/urls.py
from django.urls import path, re_path
from . import views as auths_views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls import include



app_name = 'auths'

urlpatterns = [
    path('register/', auths_views.register, name="register"),
    path('home/', TemplateView.as_view(template_name="auths/home.html"), name="home"),
    path('login/', auths_views.login, name='login'),
    path('verifymail/', auths_views.verifyEmail, name='verifyEmail'),
    path('logout/', auths_views.logout_, name='logout'),
    path('social-auth/', include('social_django.urls', namespace="social")),
    # path('register_oauth/', auths_views.register_oauth, name="register_oauth"),
    path('account_activation_sent/', auths_views.account_activation_sent, name='account_activation_sent'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
    	auths_views.activate, name='activate'),
    path('resendmail/' , auths_views.resendMail, name='resendMail'),
    
]

ca/urls.py
from django.urls import path
from . import views

app_name = 'ca'

urlpatterns = [
    path('home', views.home, name='home'),
    path('contact', views.contactUs , name='contactUs'),
    path('faqs', views.faqs , name='faqs'),
    # path('venue', views.venue , name='venue'),
    path('questionnaire', views.questionnare, name='questionnare'),
    path('pending', views.pending, name='pending'),
    path('guidelines', views.guidelines, name='guidelines'),
    path('hospitality', views.hospitality, name='hospitality'),
    path('poc', views.poc, name='poc'),
    path('submitideas', views.submitIdea, name='submitIdea'),
    path('standings', views.standings, name='standings'),
    path('notifications', views.notifications, name='notifications')
]

auths/models.py
from django.db import models
from django.contrib.auth.models import User

# class Interest(models.Model):
#         name = models.CharField(max_length=50)

#         def __str__(self):
#                 return self.name

class Profile(models.Model):
        user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
        alcher_id = models.CharField(max_length=20, unique=True)
        fullname = models.CharField(max_length=200)
        phone = models.CharField(max_length=11)
        college = models.CharField(max_length=100)
        profile_image = models.ImageField(upload_to ='profile/' ,default="profile/profile.png")
        GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ]
        gender = models.CharField(
                choices = GENDER_CHOICES,
                max_length=1,
                default='M'
                )
        # interests = models.ManyToManyField(Interest)
        # emailVerified = models.BooleanField(default=False)
        def __str__(self):
                return self.alcher_id


class CA_Detail(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='ca_details')
    ca_profile_complete = models.BooleanField(default=False)
    ca_approval = models.BooleanField(default=False)
    certificate_approval=models.BooleanField(default=False)
#     timestamp = models.DateTimeField(auto_now_add=True)
#     triweekly = models.IntegerField(default =0,verbose_name='Tri-weekly Score')
    score = models.IntegerField(default = 0)
    fbscore = models.IntegerField(default =0)

    def __str__(self):
       return f'{self.user.username} ca_detail'    

auths/views.py
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import Profile, CA_Detail
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.validators import EmailValidator, RegexValidator
from .utilities import generateAlcherId



def login(request):
        username = password = ''
        if request.POST:
                email = request.POST['ca_email']
                password = request.POST['ca_password']

                data = {}
                try:
                        email_validator = EmailValidator()
                        email_validator(email)
                except Exception as e:
                        data['email_error'] = "Please enter a valid Email ID"

                if password == '':
                        data['password_error'] = "Password is required"

                if data:
                        return render(request, 'auths/ca_login.html', data)

                user_obj = User.objects.filter(email=email)
                if len(user_obj) == 0:
                        print("No user with this email exists!")
                        data['login_error'] = "Sorry! Invalid credentials. Try again."
                        return render(request, 'auths/ca_login.html', data)
                else:
                        user = authenticate(username=user_obj[0].username, password=password)
                        if user is None:
                                print("Please enter the correct password for your account.")
                                data['login_error'] = "Sorry! Invalid credentials. Try again."
                                return render(request, 'auths/ca_login.html', data)


                        # user_obj = user_obj.filter(profile__emailVerified=True)

                        # if len(user_obj) == 0:
                        #         print("Email not verified yet!")
                        #         return redirect('auths:verifyEmail')
                        
                        
                        auth_login(request, user)
                        print(user.username)

                        ca_detail = CA_Detail.objects.filter(user = request.user);
                        if len(ca_detail) == 0:
                                CA_Detail.objects.create(user=request.user)
                                ca_detail = CA_Detail.objects.filter(user = request.user);
                        if ca_detail[0].ca_approval :
                                return redirect('ca:home')
                        elif ca_detail[0].ca_profile_complete :
                                return redirect('ca:pending')
                        else :
                                return redirect('ca:questionnare')
        return render(request, 'auths/ca_login.html')


def register(request):
        if request.method == 'POST':
                print(request.POST, "$$$$$$$$$$$$$$$$$$$$$")
                password = request.POST['password']
                fullname = request.POST['fullname']
                gender = request.POST.get('gender')
                team_name = request.POST['team_name']
                email = request.POST['email']
                phone = request.POST['phone']
                data = {}
                name_validator = RegexValidator('^[A-Za-z, ]+$')
                if fullname == '':
                        data['fullname_error'] = "Please enter your Full Name"
                else:
                        try:
                                name_validator(fullname)
                        except Exception as e:
                                data['fullname_error'] = "Only letters and white spaces"


                if email == '':
                        data['email_error'] = "Please enter a valid Email ID"
                else:
                        try:
                                email_validator = EmailValidator()
                                email_validator(email)
                        except Exception as e:
                                data['email_error'] = "Invalid email format"


                if phone == '':
                        data['phone_error'] = "Please enter a valid Phone No"
                else:
                        try:
                                phone_number_validator = RegexValidator('^[0-9]{10}$')
                                phone_number_validator(phone)
                        except Exception as e:
                                data['phone_error'] = "Must have 10 digits and only digits from 0 to 9 allowed"


                # data['phone_error'] = "Testing"
                # data['gender_error'] = "Testing"
                # data['team_name_error'] = "Testing"
                # data['fullname_error'] = "Testing"


                if gender == None:
                        data['gender_error'] = "Gender is mandatory"

                if team_name == '':
                        data['team_name_error'] = "Please enter your Team Name"
                else:
                        try:
                                name_validator(team_name)
                        except Exception as e:
                                data['team_name_error'] = "Only letters and white spaces"

                if password == '':
                        data['password_error'] = "Password is required"
                else:
                        if len(password) < 8:
                                data['password_error'] = "Password should have minimum 8 characters"


                if data:
                        print(data, "$$$$$$$$$$$$$$$$$$$$$")
                        return render(request, 'auths/ca_register.html', data)


                alcher_id = generateAlcherId(fullname)
                # if User.objects.filter(email=email).filter(profile__emailVerified=True):
                if User.objects.filter(email=email):
                        data['signup_error'] = "Make sure you are registering with your email address"
                        return render(request, 'auths/ca_register.html', data)
                else:
                        User.objects.create_user(alcher_id, email, password)
                        user = authenticate(username=alcher_id, password=password)
                        if user is not None:
                                user.is_active=True
                                profUser = Profile(user=user, alcher_id=alcher_id, fullname=fullname, phone=phone, college=team_name, gender=gender)
                                profUser.save()
                                user.save()
                                auth_login(request,user)
                                print(user)
                                CA_Detail.objects.create(user=request.user)

                                # CA_Detail.objects.create(user = request.user)

        #                         profUser.emailVerified = False
        #                         profUser.save()
                                # current_site = get_current_site(request)
        #                         subject = 'Get started with your journey of becoming Campus Ambassador for Alcheringa 2021'
        #                         message = render_to_string('auths/account_activation_email.html', {
        #         'user': user,
        #         'domain': current_site.domain,
        #         'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        #         'token': account_activation_token.make_token(user),
        #     })
        #                         user.email_user(subject, message)
                                return redirect('ca:home')
                        else: 
                                print("user is none")
                                return redirect('auths:register')

        else:
                name_pattern = "[A-Za-z ]*"
                team_name_pattern = "[A-Za-z0-9, ]*"
                phone_pattern = "[0-9]{10}"
                context = {
                'name_pattern': name_pattern,
                'team_name_pattern' : team_name_pattern,
                'phone_pattern' : phone_pattern,
                }
                return render(request, 'auths/ca_register.html', context)


def register_oauth(request):
        if request.method == 'POST':
                print(request.POST, "$$$$$$$$$$$$$$$$$$$$$")
                gender = request.POST.get('gender')
                team_name = request.POST['team_name']
                phone = request.POST['phone']
                data = {}
                name_validator = RegexValidator('^[A-Za-z ]+$')
                # email = request.POST["email"]


                if phone == '':
                        data['phone_error'] = "Please enter a valid Phone No"
                else:
                        try:
                                phone_number_validator = RegexValidator('^[0-9]{10}$')
                                phone_number_validator(phone)
                        except Exception as e:
                                data['phone_error'] = "Must have 10 digits and only digits from 0 to 9 allowed"

                if gender == None:
                        data['gender_error'] = "Gender is mandatory"

                if team_name == '':
                        data['team_name_error'] = "Please enter your Team Name/College Name"
                else:
                        try:
                                name_validator(team_name)

auths/templates/auths/CAadmin.html
{% extends 'admin/change_list.html' %}
<br>
{% block object-tools %}
    <div>
        <form action="resetscore/" method="POST">
            {% csrf_token %}
                <button style="background-color: red; cursor: pointer;" type="submit"><h3 style="color: white;">Reset Triweekly Scores</h3></button>
        </form>
    </div>
    <br>
    {{ block.super }}
{% endblock %}

auths/templates/auths/account_activation_email.html
{% autoescape off %}
Hi {{ user.profile.fullname }},
Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'auths:activate' uidb64=uid token=token %}
{% endautoescape %}

auths/templates/auths/account_activation_sent.html
{% extends 'base.html' %}
    {% load static %}



{% block title %} Signup | Campus Ambassador | Alcheringa, IIT Guwahati{% endblock %}

{% block content %}
<div style="display:grid;place-items:center;flex:1 ; height : auto ;max-width:500px" class="w3-container w3-padding">
<div>
<div class="w3-container w3-round-large" style="background:#ffffff">
  
  <div class="w3-panel w3-blue w3-card-4 w3-round-large" style="padding:5px 10px 5px 10px">
    <div class="w3-container"><h4>Good to know you,</h4>
  <p>An activation mail has been sent to your Email ID
  </div>
  </div>
  
  <div class="w3-container">
      <ol>
					<p><strong>PLEASE NOTE</strong>: If you didn't receive an email from us-</p>
					<li>Check your Promotion/Updates/Spam/Junk Folder</li>
					<li>Keep in mind, it can take a while, even a few hours for you to receive your email confirmation.</li>
					<li>You can try to fill in the form once again, remember to make sure your email address is correct.</li>
					<li>Remember to mark our Email ID 'publicrelations@alcheringa.in' as important so that all future emails directly go to your inbox.</li>
					<li>If you still haven't received any mail or the confirmation link is not working, kindly let us know by sending an email at publicrelations@alcheringa.in. We will be happy to help you out.</li>
				</ol>
				<!-- <a href="https://www.alcheringa.in/registrations/index.php" alt="Login page" style="margin: 0 auto;/*! position: relative; */display: block;margin-bottom: 20px;" class="w3-button w3-round-medium w3-center w3-blue">Go to Registration Portal Login</a> -->
				<a href="{% url 'auths:login' %}" alt="Login page" style="margin: 0 auto;/*! position: relative; */display: block;margin-bottom: 20px;" class="w3-button w3-round-medium w3-center w3-blue">Go to CA Portal Login</a>
				<a href="{% url 'auths:register' %}" alt="Login page" style="margin: 0 auto;/*! position: relative; */display: block;margin-bottom: 20px;" class="w3-button w3-round-medium w3-center w3-blue">Go to CA Portal Register</a>
      
  </div>
  
</div>
</div>
</div>
{% endblock %}

auths/templates/auths/ca_oauth_register.html
{% extends 'base.html' %}
    {% load static %}



{% block title %} Signup | Campus Ambassador | Alcheringa, IIT Guwahati{% endblock %}

{% block content %}
<div style="display:grid;place-items:center;flex:1 ; height : auto ;">
 <div>                      
<div class="container" style="height : auto;">

  
    <div class="row">
    	 {% if messages %}
        {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

        {% endfor %}

    {% endif %}
      <h4 style="text-align:center;text-transform:uppercase">Campus Ambassador Portal</h4>
      
      <div style="max-width:320px;padding:0 5px 0 5px;margin-left:auto;margin-right:auto;">
      <p style="color:#767676;direction:ltr">Campus ambassadors are our representatives in your college. Work with us to make <b style='color:#000'>Alcheringa</b> bigger and better.</p>
      <br>
      </div>
      
      <!-- <div class="vl">
        <span class="vl-innertext">or</span>
      </div> -->


      <div class="col" style="width: 25vw;">
		  
        <!-- <div class="hide-md-lg">
          <p>Or sign up manually:</p>
          
        </div> -->
        <div class="sign_up_error" style="color:#d50000;font-size:11px;">
			{{signup_error}}
						
	    </div>
        
        
        <form id='create_account_form' action='' method='POST'>
            {% csrf_token %}
                                                      <!---  <div class="email_div">

								<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
									<input class="mdl-textfield__input" type="email" id="email" name="email"
									value="{{ user.email }}">
									<label class="mdl-textfield__label" for="email">Email Id</label>
									<span class="mdl-textfield__error">Please enter a valid Email ID</span>
									<span class="email_error input_error"><p>{{email_error}}</span>
								</div>


							</div>


						--->

							<div class="phone_div">
								<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
									<input class="mdl-textfield__input" type="tel" id="phone" name="phone"
									value="" pattern="{{phone_pattern}}">
									<label class="mdl-textfield__label" for="phone">Phone Number</label>
									<span class="mdl-textfield__error">Please enter a valid Phone No</span>
									<div class="phone_error input_error"><p>{{phone_error}}</p></div>
								</div>
							</div>


							<div class="gender_div">
								<label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="gender_male">
									<input type="radio" id="gender_male" class="mdl-radio__button" name="gender"
									value="M">
									<span class="mdl-radio__label">Male</span>
								</label>
								<label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="gender_female">
									<input type="radio" id="gender_female" class="mdl-radio__button" name="gender"
									value="F">
									<span class="mdl-radio__label">Female</span>
								</label>

								<div class="gender_error input_error"><p>{{gender_error}}</p></div>
							</div>

							<div class="team_name_div">

								<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
									<input class="mdl-textfield__input" type="text" id="team_name" name="team_name"
										value="" pattern="{{team_name_pattern}}">
									<label class="mdl-textfield__label" for="team_name">College/Institute/Team Name</label>
									<span class="mdl-textfield__error">Only letters, digits, comma and space are allowed</span>
									<div class="team_name_error input_error"><p>{{team_name_error}}</p></div>
								</div>
							</div>                  
							<!-- <div class="interests_div">
								Pick Your Interests -->
								<!-- <select name='interests[]' form='create_account_form' multiple id='interests' class="ui fluid search dropdown">
									{% for interest in interests_list %}
									<option value='{{interest.id}}'>{{interest.name}}</option>
									{% endfor %}
								</select> -->
								<!-- <i class="dropdown-icon">::before</i>
								<input class="search valid" autocomplete="off" tabindex="0" aria-invalid="false">
								<span class="sizer"></span>

								<div class="menu transition hidden" tabindex="-1">
									<div class="item selected" data-value="Dance">Dance</div>
									<div class="item" data-value="Music">Music</div>
									<div class="item" data-value="Drama">Drama</div>
									<div class="item" data-value="Fashion">Fashion</div>
									<div class="item" data-value="Arts">Arts</div>
									<div class="item" data-value="Literature">Literature</div>
									<div class="item" data-value="Quiz">Quiz</div>
									<div class="item" data-value="Sports">Sports</div>
									<div class="item" data-value="CA">CA</div>
								</div> -->
								<!-- <div class="interests_error input_error"><p>{{interests_error}}</p></div>
							</div> -->

							

							<div class="sign_up">
							    <button style="" name="create_account" id="ca_login_button" class="btn">CREATE ACCOUNT</button>
								
							</div>

		</form>
        <!-- -->
      
      </div>
      <div class="col">
                        
        
	</div>
    </div>
  
  
</div>

<div class="bottom-container">
  <!-- <div class="row">
    <div class="col-12">
      <a href="{% url 'auths:login' %}" style="color:white" class="btn">Login </a>
    </div>
    
  </div> -->
</div>
</div>
</div>

{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'ca/js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'ca/js/drawer.js' %}"></script>
	<script type="text/javascript" src="{% static 'ca/js/functions.js' %}"></script>
	<script type="text/javascript" src="{% static 'ca/js/jquery_ui/jquery-ui.min.js' %}"></script>
	<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
	<script type="text/javascript" src="{% static 'ca/semantic/dist/semantic.min.js' %}"></script>
	<script type="text/javascript">
		$(function(){
			$('#interests').dropdown();

			$('.login_form_slider').click(function(){
				var $this= $(this);
				$this.parent().slideUp(function(){
					$this.parent().next().slideDown();
				});
				
			});

			$('#sign_up_button').click(function(){
				$('.login_div').slideUp(function(){
					$('.sign_up_div').slideDown();
				});
				$('#sign_up_button').animate({'background-color': '#2abfbf', 'color': 'white'}, 400);
				$('#login_button').animate({'background-color': 'white', 'color': '#2abfbf'}, 400);
			});
			$('#login_button').click(function(){
				$('.sign_up_div').slideUp(function(){
					$('.login_div').slideDown();
					$('.login_div').css({'display': 'flex'});
				});
				$('#login_button').animate({'background-color': '#2abfbf', 'color': 'white'}, 400);
				$('#sign_up_button').animate({'background-color': 'white', 'color': '#2abfbf'}, 400);
			});
			
		});
	</script>
{% endblock %}
					
				

auths/templates/auths/ca_register.html
{% extends 'base.html' %}
    {% load static %}



{% block title %} Signup | Campus Ambassador | Alcheringa, IIT Guwahati{% endblock %}

{% block content %}
<div style="margin-top:10px;display:grid;place-items:center;flex:1 ; height : auto ;">
<div>
                        
<div class="container" style="height : auto;">
  
    <div class="row">
    	 {% if messages %}
        {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

        {% endfor %}

    {% endif %}
      <h4 style="text-align:center;text-transform:uppercase">Campus Ambassador Portal</h4>
      
      <div style="max-width:320px;padding:0 5px 0 5px;margin-left:auto;margin-right:auto;">
      <p style="color:#767676;direction:ltr">Campus ambassadors are our representatives in your college. Work with us to make <b style='color:#000'>Alcheringa</b> bigger and better.</p>
      <br>
      </div>
      
      <!-- <div class="vl">
        <span class="vl-innertext">or</span>
      </div>

      <div class="col">
		<a href="{% url 'auths:social:begin' 'facebook' %}" class='fb btn'>
			<i class='fa fa-facebook fa-fw'></i> Login with Facebook
		</a>
        
      </div> -->

      <div class="col" style="width: 100%;">
        <!-- <div class="hide-md-lg">
          <p>Or sign up manually:</p>
          
        </div> -->
        <div class="sign_up_error" style="color:#d50000;font-size:15px;">
			{{signup_error}}
						
	    </div>
        
        
        <form id='create_account_form' action='' method='POST'>
            {% csrf_token %}

							<div class="fullname_div">

								<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
									<input class="mdl-textfield__input" type="text" id="fullname" name="fullname"
									value="" pattern="{{name_pattern}}">
									<label class="mdl-textfield__label" for="fullname">Full Name</label>
									<span class="mdl-textfield__error">Only letters and white spaces are allowed</span>
									<span class="fullname_error input_error">{{fullname_error}}</span>
								</div>


							</div>

							<div class="email_div">

								<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
									<input class="mdl-textfield__input" type="email" id="email" name="email"
									value="">
									<label class="mdl-textfield__label" for="email">Email ID</label>
									<span class="mdl-textfield__error">Please enter a valid Email ID</span>
									<span class="email_error input_error"><p>{{email_error}}</span>
								</div>


							</div>

							<div class="phone_div">

								<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
									<input class="mdl-textfield__input" type="tel" id="phone" name="phone"
									value="" pattern="{{phone_pattern}}">
									<label class="mdl-textfield__label" for="phone">Phone Number</label>
									<span class="mdl-textfield__error">Please enter a valid Phone No</span>
									<span class="phone_error input_error">{{phone_error}}</span>
								</div>


							</div>

							<div class="gender_div">
								<label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="gender_male">
									<input type="radio" id="gender_male" class="mdl-radio__button" name="gender"
									value="M">
									<span class="mdl-radio__label">Male</span>
								</label>
								<label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="gender_female">
									<input type="radio" id="gender_female" class="mdl-radio__button" name="gender"
									value="F">
									<span class="mdl-radio__label">Female</span>
								</label>
								<br>
								<span class="gender_error input_error">{{gender_error}}</span>

							</div>

							<div class="team_name_div">

								<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
									<input class="mdl-textfield__input" type="text" id="team_name" name="team_name"
										value="" pattern="{{team_name_pattern}}">
									<label class="mdl-textfield__label" for="team_name">College/Institute/Team Name</label>
									<span class="mdl-textfield__error">Only letters, digits, comma and space are allowed</span>
									<span class="team_name_error input_error">{{team_name_error}}</span>
								</div>


							</div>

							<!-- <div class="interests_div">
								Pick Your Interests
								<select name='interests[]' form='create_account_form' multiple id='interests' class="ui fluid search dropdown">
									
									{% for interest in interests_list %}
									<option value='{{interest.id}}'>{{interest.name}}</option>
									{% endfor %}

								</select>

								<span class="interests_error input_error">{{interests_error}}</span>
							</div> -->

							<div class="password_div">

								<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
									<input class="mdl-textfield__input" type="password" id="password" name="password" pattern="[^\s]+">
									<label class="mdl-textfield__label" for="password">Password (min 8 chars required.)</label>
									<span class="mdl-textfield__error">White spaces are not allowed</span>
									<span class="password_error  input_error">{{password_error}}</span>
								</div>


              </div>
              {% comment %} <div class="form_general_error input_error style='display: block "><p>{{form_general_error}}</p></div> {% endcomment %}

							<div class="sign_up">
							    <button style="" name="create_account" id="ca_login_button" class="btn">CREATE ACCOUNT</button>
								
							</div>

		</form>
        <!-- -->
      
      </div>
      
    </div>
  
  
</div>

<div class="bottom-container">
  <div class="row">
    <div class="col">
      <a href="{% url 'auths:login' %}" style="color:white" class="btn">Login </a>
    </div>
    
  </div>
</div>
</div>
</div>
					
{% endblock %}

{% block js %}

<script type="text/javascript">
		$(function(){
			// $('#interests').dropdown();

			$('.login_form_slider').click(function(){
				var $this= $(this);
				$this.parent().slideUp(function(){
					$this.parent().next().slideDown();
				});
				
			});

			$('#sign_up_button').click(function(){
				$('.login_div').slideUp(function(){
					$('.sign_up_div').slideDown();
				});
				$('#sign_up_button').animate({'background-color': '#2abfbf', 'color': 'white'}, 400);
				$('#login_button').animate({'background-color': 'white', 'color': '#2abfbf'}, 400);
			});
			$('#login_button').click(function(){
				$('.sign_up_div').slideUp(function(){
					$('.login_div').slideDown();
					$('.login_div').css({'display': 'flex'});
				});
				$('#login_button').animate({'background-color': '#2abfbf', 'color': 'white'}, 400);
				$('#sign_up_button').animate({'background-color': 'white', 'color': '#2abfbf'}, 400);
			});
			
		});
  </script>
		{% endblock %}
  

auths/templates/auths/home.html
{% if user.is_authenticated %}
	{{user.username}}
	<a class="btn btn-primary" href="{% url 'auths:logout' %}">Logout</a>
{% endif %}